The Age of Democracy, continued.
========================================================
(Part of an occasional series on [the history of political regimes](http://abandonedfootnotes.blogspot.co.nz/search/label/history%20of%20political%20regimes))

This is the age of democracy. As I noted in [an earlier post](http://abandonedfootnotes.blogspot.com/2013/02/the-normativeness-of-democracy.html), almost every state in the world mentions the word "democracy" or "democratic" in its constitutional documents today. But the public acknowledgment of the idea of democracy in constitutional documents is not something that just began a few years ago; in fact, it goes back much further, all the way back to the nineteenth century in a surprising number of cases. 

Here is a figure I've been wanting to make for a while that makes this point nicely (based on data graciously made available by the [Comparative Constitutions Project](http://comparativeconstitutionsproject.org/); from a project I'm working on). The figure shows all countries that have ever had some kind of identifiable constitutional document (broadly defined) that mentions the word "democracy" or "democratic" (in any context - new constitution, amendment, interim constitution, bill of rights, etc.), arranged from earliest to latest mention. Each symbol represents a "constitutional event" - a new constitution adopted, an amendment passed, a constitution suspended, etc. - and colored symbols indicate that the text associated with the constitutional event in question mentions the word "democracy" or "democratic" (see [data and methods note below](#DataAndMethods) for more details): 

```{r DemocConstitutions, echo=FALSE, fig.height=27, fig.width=8.1, warning=FALSE}
library(ggplot2)
democracy.mentions <- read.csv("democracy.mentions.csv",fileEncoding="native.enc")

data <- democracy.mentions[ !(democracy.mentions$EVENTTYPE %in% c("international convention","non-event","draft")) & !is.na(democracy.mentions$earliest.dem),]
data$EVENTTYPE <- relevel(data$EVENTTYPE,"new")
data$democracy.event <- as.factor(data$democracy.event)
data$democracy.event <- relevel(data$democracy.event,"new")
levels(data$democracy.event) <- c("new const.","amended const.","draft const.","interim const.","international convention","non-event","reinstated const.","suspended const.")

democConstitutions <- ggplot() + geom_point(data=data, aes(x=reorder(COUNTRY,-earliest.dem),y=YEAR,color=democracy.event, shape=EVENTTYPE)) + coord_flip() + theme_bw() + theme(legend.position="top") + labs(color="Mention of democracy in:", x="Country", y= "Year", shape="Type of constitutional event:")

democConstitutions <- democConstitutions + ylim(c(1760,2013)) + geom_hline(yintercept=c(min(democracy.mentions$earliest.dem,na.rm=TRUE),1914,1918,1939,1945,1989),color="red") + scale_color_discrete(na.value="lightgrey") + annotate("rect",xmin=1,xmax=length(unique(as.character(data$COUNTRY)))+1,ymin=1914,ymax=1918,fill="grey50",alpha=0.2)+annotate("rect",xmin=1,xmax=length(unique(as.character(data$COUNTRY)))+1,ymin=1939,ymax=1945,fill="grey50",alpha=0.2)
democConstitutions + guides(color = guide_legend(ncol=2), shape = guide_legend(ncol=2))
```
(Red lines indicate, from left to right, the date of the first mention of the word "democracy" or "democratic" in a constitutional text, WWI, WWII, and the end of the Cold War [1989]).

The earliest mention of the word "democracy" or "democratic" in a constitutional document occurred in Switzerland and France in 1848, as far as I can tell.[[1](#Note1)] Participatory Switzerland and revolutionary France look like obvious candidates for being the first countries to embrace the "democratic" self-description; yet the next set of countries to embrace this self-description (until the outbreak of WWI) might seem more surprising: they are *all* Latin American or Caribbean (Haiti), followed by countries in Eastern Europe (various bits and pieces of the Austro-Hungarian empire), Southern Europe (Portugal, Spain), Russia, and Cuba. Indeed, most "core" countries in the global system did not mention democracy in their constitutions until much later, if at all, despite many of them having long constitutional histories; even French constitutions after the fall of the [Second Republic](http://en.wikipedia.org/wiki/French_Second_Republic) in 1851 did not mention "democracy" until after WWII. In other words, the *idea* of democracy as a value to be publicly affirmed seems to have caught on first not in the metropolis but in the periphery, and especially in "post-colonial" places (as in all the countries that became independent after WWII); democracy is the post-imperial public value *par excellence*, asserted after national liberation or revolutions against hated monarchs (e.g., Egypt 1956, Iran 1979, both of them the first mentions of democracy in these countries but not their first constitutions). 

Today, however, only 16 countries have ever failed to mention their "democratic" character in their constitutional documents (Australia, Brunei, Denmark, Japan, Jordan, Malaysia, Monaco, Nauru, Oman, Samoa, Saudi Arabia, Singapore, Tonga, the United Kingdom, the USA, and Vatican City).[[2](#Note2)] And no country that has ever mentioned "democracy" in an earlier constitutional document fails to mention it in its current constitutional documents (though some countries in the 19th and early 20th centuries went back and forth - mentioning democracy in one constitution, not mentioning it in the next). Indeed, after WWII the first mention of democracy in constitutions tended to be contemporaneous with the first post-independence constitution of the country; and with time, even countries with old and settled constitutional traditions seem to be more and more likely to mention "democracy" or "democratic" in some form as amendments or bills of rights accumulate (e.g., Belgium in 2013, [New Zealand in 1990](http://www.legislation.govt.nz/act/public/1990/0109/latest/DLM224792.html), Canada in 1982, Finland in 1995). The probability of a new constitution mentioning "democracy" appears to be asymptotically approaching 1. To use the language of biology, the democratic "meme" has nearly achieved "[fixation](http://en.wikipedia.org/wiki/Fixation_(population_genetics))" in the population, despite short-term fluctuations, and despite the fact that there appears to be no particular correlation between a state *calling* itself democratic and actually *being* democratic, either today or in the past.[[3](#Note3)]

Though the actual "measured" level of democracy around the world has trended upwards (with some ups and downs) [over the last two centuries](http://abandonedfootnotes.blogspot.com/2012/09/the-great-norm-shift-and-triumph-of.html), I don't think this is the reason why the idea of democracy has achieved near-universal recognition in public documents. Countries do not first become democratic and then call themselves democracies; if anything, most mentions of democracy seem to be rather aspirational, if not entirely cynical, though many were also produced by people who seem to have been genuinely committed to some such ideal, however misguided, and even if the regimes that eventually developed under these constitutions were not particularly democratic. What we see, instead, is a broad process in which earlier normative claims about the basis of authority - monarchical, imperial, etc. - get almost completely replaced, regardless of the country's cultural context, by democratic claims, regardless of the latter's effectiveness as an actual basis for authority or the existence of working mechanisms for participation or vertical accountability. (These democratic claims to authority also sometimes coexist in uneasy tension with other claims to authority based on divine revelation, ideological knowledge, or tradition, invented or otherwise; consider the [Chinese constitution](http://english.people.com.cn/constitution/constitution.html)'s claims about the "people's democratic dictatorship" led by the CCP). 

I thus suspect the conquest of ideological space by "democratic" language did not happen just because democratic claims to authority (especially in the absence of actual democracy) have proved more persuasive than other claims to authority. Rather, I think the same processes that resulted in the emergence of modern national communities - e.g. the rituals associated with the nationalism, which tended to "[sacralize](http://abandonedfootnotes.blogspot.com/2013/04/engines-of-sacrality-footnote-on.html)" a particular kind of [imagined community](http://books.google.co.nz/books?id=nQ9jXXJV-vgC) - led to the symbolic production of the nation not only as the proper *object* of government but also as its proper *active agent* (the people, actively ruling itself), regardless of whether or not "the people" had any ability to rule or even to exercise minimal control over the rulers.[[4](#Note4)] There thus seems to have been a kind of co-evolution of symbols of nationality and symbols of democracy, helped along by the practice/ritual of drafting constitutions and approving them through plebiscites or other forms of mass politics, a ritual that already makes democratic assumptions about "social contracts." The question is whether the symbolic politics of democracy eventually has any sort of impact on actual institutions. But more on this later.

### <a name="DataAndMethods"></a> Data and Methods

The underlying texts used to construct this figure have been gathered by the [Comparative Constitutions Project](http://comparativeconstitutionsproject.org/). What "counts" as a constitutional document is subject to some debate, especially in countries like the UK or New Zealand that are sometimes said not to have a written constitution. But all of the documents gathered by the CCP are indisputably important, describing basic structures of government and setting out the rights of citizens. Unfortunately, however, most are not publicly available through the CCP repository due to copyright complications. I thank [Zachary Elkins](http://www.utexas.edu/cola/depts/government/faculty/elkinszs), one of the CCP Principal Investigators, for granting me access to them; I also want to note that the work of the CCP in collecting, categorizing, and coding them is invaluable (and hopefully may soon be more widely accessible, with the [Constitute website](https://www.constituteproject.org/#/)). 

Anyway, in order to create these figures, I downloaded the PDFs of all the documents in their archive and extracted the text of as many as I could using the [Python PDFminer library](http://www.unixuser.org/~euske/python/pdfminer/). (Some of the older constitutions have not been OCRd, and a few are password-protected, so there's no text for them; see the the "[inventory]()" file for details). I then used [this R script]() to extract each mention of the word "democracy." Specifically, I identified each line that contained the pattern "democ" or "demok" or "mocra" or "demo-" in every extracted text file (not all of the available texts are in English, but the word "democracy" has similar roots in most European languages at least), as well as the previous and the following line, and put them in a table. I then inspected this table for false positives - instances where the algorithm picks up the word "democracy" in cases where it isn't actually mentioned in the constitutional text, or instances, mostly in poorly-OCRd Cyrillic texts, where the algorithm picks up words that contain the pattern "mocra" are not "democracy" or "democratic" (or any variant). The exact list of false positives is available in [this R script](), as well as all the changes made to the original list of mentions. Finally, I calculated earliest and latest mentions of democracy (as well as a few other dates). All code (plus the resulting dataset of democracy mentions) is available in [this GitHub repository](). 

### Notes

<a name="Note1">[1]</a> It is *possible* that there is an earlier mention of democracy in the data; I have not manually checked every earlier constitutional document, and some of them are poorly OCRd and not in a major language. But France and Switzerland seem right.

<a name="Note2">[2]</a> Some mentions of democracy occur only in passing, as in New Zealand, where a [1990 bill of rights](http://www.legislation.govt.nz/act/public/1990/0109/latest/DLM224792.html) (counted by the CCP as an "amendment" to New Zealand's constitution) has a section on "democratic and civil rights" and indicates that restrictions on rights must be demonstrably justified in a manner appropriate to "a free and democratic society." One could easily come up with a story linking most of the countries that do *not* mention democracy: it's basically countries whose constitutional documents are still strongly influenced by a UK or USA constitutional legacy in Asia, due to a relatively stable post-colonial or post-war history (e.g., Malaysia, Singapore, Japan) and monarchies whose sovereigns are still relatively unconstrained (e.g., Saudi Arabia, Oman, Tonga). 

<a name="Note3">[3]</a> This is tricky to check with an actual measure of democracy for a variety of reasons (though I'm working on it), but at least [today](http://abandonedfootnotes.blogspot.com/2013/02/the-normativeness-of-democracy.html) there's no correlation. I do wonder whether a long history of mentions is correlated with democracy today - aspiration becoming reality, as it were - or whether the correlation between mentions of democracy and actual levels of democracy has varied through time (perhaps the language of democracy once meant something but today it does not, for example).

<a name="Note4">[4]</a> For a fuller academic argument on this point, see my piece on "Models of Political Community" [here](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1104893). I think a similar process once took place in the late Roman Republic, as I argued in a piece on "[Cicero's Conception of the Political Community](http://muse.jhu.edu/books/9780268087630)" [ungated here](https://docs.google.com/open?id=0B5XMXc9uWFRvODc2YjUyNTYtNGYyZi00YTJlLTkwMWItMDdlYjljZjJkNzgx): Cicero almost came to the idea of a "national" state and "representative" institutions.